
POST https://webdev-backend-n0v3.onrender.com/quote-request HTTP/1.1
content-type:application/json

{
    "firstName": "Jk1103269", 
    "lastName": "Pokemoncards1", 
    "email": "jordankraudetp@gmail.com", 
    "phoneNumber": "2094952253", 
    "budget": "$5,000 - $10,000"
}


###
POST https://webdev-backend-n0v3.onrender.com/feedback/ HTTP/1.1
content-type:application/json

{
  "firstName": "Jordan",
  "lastName": "Kraude",
  "email": "jordankraudetp@gmail.com",
  "feedback": "I hate this compan",
  "wantResponse": "No"
}