
POST http://localhost:8000/quote-request HTTP/1.1
content-type:application/json

{
    "firstName": "Jk1103269", 
    "lastName": "Pokemoncards1", 
    "email": "jordankraudetp@gmail.com", 
    "phoneNumber": "2094952253", 
    "budget": "20,000"
}


###
POST http://localhost:8000/feedback HTTP/1.1
content-type:application/json

{
  "firstName": "Jordan",
  "lastName": "Kraude",
  "email": "jordankraudetp@gmail.com",
  "feedback": "I hate this company",
  "likeResponse": "No"
}